Pega Pool
mempool/mining-pools pull request #20
Opened 2022-11-05 08:08 UTC by Read1337

added Pega Pool

2022-11-05 08:08 UTC, Read1337 commented
Sry about last PR, this shoud be ok

2022-11-08 18:50 UTC, nymkappa requested changes

2022-11-08 19:03 UTC, Read1337 commented on pools.json
> +        "Pega Pool": "pegapool"
Changed

2022-11-09 05:57 UTC, nymkappa requested changes
Thanks. It's good now but can you squash your PR to only make it one commit with proper commit description please? Then we can merge it.

2022-11-10 09:13 UTC, nymkappa approved these changes
Tested ACK @ 572de81515f39b7ae31f86cae572d943dfc7ab6d

<img width="702" alt="image" src="https://user-images.githubusercontent.com/9780671/201050700-5ebe34cd-5fff-4a05-9175-f163bd497e81.png">

2022-11-14 14:23 UTC, Read1337 commented
Hey, Do I need to do anything else? We would love to see PEGA Pool stats on mempool.space let me know if there is anything else we need to do.

2022-12-26 13:33 UTC, merged